
development:
  adapter: postgresql
  encoding: unicode
  database: RocketDrop_development
  pool: 5



test:
  adapter: postgresql
  encoding: unicode
  database: RocketDrop_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: RocketDrop_production
  pool: 5

